// Shared enums that match Prisma schema
// These should be kept in sync with backend/prisma/schema.prisma

export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN'
}

export enum RecordType {
  PRESCRIPTION = 'PRESCRIPTION',
  DIAGNOSIS = 'DIAGNOSIS',
  LAB_RESULT = 'LAB_RESULT',
  IMAGING = 'IMAGING',
  VACCINATION = 'VACCINATION',
  DISCHARGE_SUMMARY = 'DISCHARGE_SUMMARY',
  OTHER = 'OTHER'
}

export enum VitalType {
  HEART_RATE = 'HEART_RATE',
  BLOOD_PRESSURE_SYSTOLIC = 'BLOOD_PRESSURE_SYSTOLIC',
  BLOOD_PRESSURE_DIASTOLIC = 'BLOOD_PRESSURE_DIASTOLIC',
  BLOOD_GLUCOSE = 'BLOOD_GLUCOSE',
  SPO2 = 'SPO2',
  TEMPERATURE = 'TEMPERATURE',
  WEIGHT = 'WEIGHT',
  HEIGHT = 'HEIGHT',
  BMI = 'BMI',
  RESPIRATORY_RATE = 'RESPIRATORY_RATE',
  OTHER = 'OTHER'
}

export enum ReminderFrequency {
  ONCE = 'ONCE',
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  CUSTOM = 'CUSTOM'
}

export enum IllnessSeverity {
  MILD = 'MILD',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
  CRITICAL = 'CRITICAL'
}

export enum IllnessStatus {
  ONGOING = 'ONGOING',
  RECOVERED = 'RECOVERED',
  RESOLVED = 'RESOLVED',
  CHRONIC = 'CHRONIC'
}

export enum VehicleType {
  CAR = 'CAR',
  SUV = 'SUV',
  PICKUP = 'PICKUP',
  MOTORCYCLE = 'MOTORCYCLE',
  TRUCK = 'TRUCK',
  VAN = 'VAN',
  OTHER = 'OTHER'
}

export enum MaintenanceType {
  OIL_CHANGE = 'OIL_CHANGE',
  BRAKE_PAD_REPLACEMENT = 'BRAKE_PAD_REPLACEMENT',
  TIRE_ROTATION = 'TIRE_ROTATION',
  TIRE_REPLACEMENT = 'TIRE_REPLACEMENT',
  BATTERY_REPLACEMENT = 'BATTERY_REPLACEMENT',
  AIR_FILTER_REPLACEMENT = 'AIR_FILTER_REPLACEMENT',
  TRANSMISSION_SERVICE = 'TRANSMISSION_SERVICE',
  COOLANT_FLUSH = 'COOLANT_FLUSH',
  SPARK_PLUG_REPLACEMENT = 'SPARK_PLUG_REPLACEMENT',
  BRAKE_FLUID_CHANGE = 'BRAKE_FLUID_CHANGE',
  ALIGNMENT = 'ALIGNMENT',
  INSPECTION = 'INSPECTION',
  REPAIR = 'REPAIR',
  OTHER = 'OTHER'
}

export enum PaymentMethod {
  CASH = 'CASH',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  MOBILE_PAYMENT = 'MOBILE_PAYMENT',
  CHECK = 'CHECK',
  OTHER = 'OTHER'
}

export enum ExpenseFrequency {
  ONE_TIME = 'ONE_TIME',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY'
}
